version: '3.8'

services:
  kariyer-recruiting:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: kz-recruiting
    restart: unless-stopped
    ports:
      - "5340:5340"
    env_file:
      - .env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kz_network

networks:
  kz_network:
    driver: bridge
