version: '3.8'

services:
  kariyer-recruiting:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: kz-recruiting
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env.development
